<?php echo $this->doctype(); ?>
<html lang="pt_BR">
<head>
	<meta charset="utf-8" />
	<?php echo $this->headTitle('NossoAmorDeuNisso | Login Page') ?>
	<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	<?php echo $this->headMeta()->appendName('description', 'Sistema do Site Mosso Amor deu nisso') ?>
	<?php echo $this->headMeta()->appendName('author', 'Daniel Chaves') ?>
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/pages/login.css')
                        ->prependStylesheet($this->basePath() . '/assets/plugins/uniform/css/uniform.default.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/themes/default.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/style-responsive.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/style-metro.css')
                        ->prependStylesheet($this->basePath() . '/assets/plugins/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/plugins/bootstrap/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/plugins/bootstrap/css/bootstrap.min.css');

         echo $this->headScript()->prependFile($this->basePath() . '/assets/scripts/login.js')
                                 ->prependFile($this->basePath() . '/assets/scripts/app.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery-validation/dist/jquery.validate.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/uniform/jquery.uniform.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery.cookie.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery.blockui.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js')
                                 //->prependFile($this->basePath() . '/assets/plugins/respond.min.js', array('conditional' => 'lt IE 9',))
                                 //->prependFile($this->basePath() . '/assets/plugins/excanvas.min.js', array('conditional' => 'lt IE 9'))
                                 ->prependFile($this->basePath() . '/assets/plugins/bootstrap/js/bootstrap.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery-migrate-1.2.1.min.js')
                                 ->prependFile($this->basePath() . '/assets/plugins/jquery-1.10.1.min.js')
	 ?>

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
	<!-- BEGIN LOGO -->
	<div class="logo">
		<img src="<?php echo $this->basePath() ?>/assets/img/logo-big.png" alt="" />
	</div>
	<!-- END LOGO -->
	<!-- BEGIN LOGIN -->
	<div class="content">
		<!-- BEGIN LOGIN FORM -->
		<form class="form-vertical login-form" action="<?php echo $this->basePath() ?>/application/auth/auth" method="post">
			<h3 class="form-title">Entre em sua conta</h3>
			<div class="alert alert-error hide">
				<button class="close" data-dismiss="alert"></button>
				<span>Usuário e Senha são obrigatórios.</span>
			</div>
			<div class="control-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9">Usuário</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-user"></i>
						<input class="m-wrap placeholder-no-fix" type="text" placeholder="Username" name="userName"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label visible-ie8 visible-ie9">Senha</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-lock"></i>
						<input class="m-wrap placeholder-no-fix" type="password" placeholder="Password" name="password"/>
					</div>
				</div>
			</div>
			<div class="form-actions">
				<label class="checkbox">
				<input type="checkbox" name="remember" value="1"/> Lembre-me
				</label>
				<input type="submit" class="btn green pull-right" name="login" value="Login">
				
			</div>
			<div class="forget-password">
				<h4>Esqueceu sua senha?</h4>
				<p>
					não se preocupe, clique <a href="javascript:;" class="" id="forget-password">aqui</a>
					para resetar.
				</p>
			</div>
			
		</form>
		<!-- END LOGIN FORM -->
		<!-- BEGIN FORGOT PASSWORD FORM -->
		<form class="form-vertical forget-form" action="<?php echo $this->basePath() ?>/application/auth/forgotpass">
			<h3 class="">Forget Password ?</h3>
			<p>Enter your e-mail address below to reset your password.</p>
			<div class="control-group">
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-envelope"></i>
						<input class="m-wrap placeholder-no-fix" type="text" placeholder="Email" name="email" />
					</div>
				</div>
			</div>
			<div class="form-actions">
				<button type="button" id="back-btn" class="btn">
				<i class="m-icon-swapleft"></i> Back
				</button>
				<button type="submit" class="btn green pull-right">
				Submit <i class="m-icon-swapright m-icon-white"></i>
				</button>
			</div>
		</form>
		<!-- END FORGOT PASSWORD FORM -->
		<!-- BEGIN REGISTRATION FORM -->
		<form class="form-vertical register-form" action="index.html">
			<h3 class="">Sign Up</h3>
			<p>Enter your account details below:</p>
			<div class="control-group">
				<label class="control-label visible-ie8 visible-ie9">Username</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-user"></i>
						<input class="m-wrap placeholder-no-fix" type="text" placeholder="Username" name="username"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label visible-ie8 visible-ie9">Password</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-lock"></i>
						<input class="m-wrap placeholder-no-fix" type="password" id="register_password" placeholder="Password" name="password"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label visible-ie8 visible-ie9">Re-type Your Password</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-ok"></i>
						<input class="m-wrap placeholder-no-fix" type="password" placeholder="Re-type Your Password" name="rpassword"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9">Email</label>
				<div class="controls">
					<div class="input-icon left">
						<i class="icon-envelope"></i>
						<input class="m-wrap placeholder-no-fix" type="text" placeholder="Email" name="email"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<label class="checkbox">
					<input type="checkbox" name="tnc"/> I agree to the <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>
					</label>
					<div id="register_tnc_error"></div>
				</div>
			</div>
			<div class="form-actions">
				<button id="register-back-btn" type="button" class="btn">
				<i class="m-icon-swapleft"></i>  Back
				</button>
				<button type="submit" id="register-submit-btn" class="btn green pull-right">
				Sign Up <i class="m-icon-swapright m-icon-white"></i>
				</button>
			</div>
		</form>
		<!-- END REGISTRATION FORM -->
	</div>
	<!-- END LOGIN -->
	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		2013 &copy; Cepheros. SegAdmin.
	</div>



	<script>
		jQuery(document).ready(function() {
		  App.init();
		  Login.init();
		});
	</script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>